{% set name = "portpicker" %}
{% set version = "1.3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/portpicker-{{ version }}.tar.gz
  sha256: 0810733c70306e6a68ee201f82155b74f6c17d655fb562f17dd6a772d0393a84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - portpicker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/python_portpicker
  summary: A library to choose unique available network ports.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jamesmyatt
